version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  app:
    build:
      context: ./app
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./app:/go/src/github.com/umpuep/app
    ports:
      - "5000:8080"
    links:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./frontend/src:/frontend/src 
    ports:
      - "3000:3000"
